### ISSUE TITLE
Junction table on db not enabling duplicate package entries

### ISSUE THREAD

**Issue by rhass-uta** [z-arnott/Vega#20]

**Comment by z-arnott** [comment]
Solution for Iteration 2:
in types.util, change package.id to package.ref
>package.ref will be the SBOM unique identifier in string format

in the database, assign a unique ID to every package that is entered
>this unique ID will be a number, and the implementation details will be hidden outside of the storage facade

Through the storage facade, key by package.ref and use session ID to resolve collisions
>eg. read(package_ref, sessionID) write(package, sessionID)
